### ISSUE TITLE
怎么没有第二张类似朋友圈的demo ?

### ISSUE THREAD

**Issue by xuekaiqi** [hnsugar/CommentListTextView#1]
你给出的只是第一张的实例，第二张例子怎么没有代码？  而且你这个使用环境在什么情况下？

我评论肯定是listview 展示的！你这样是listview的item?

**Comment by hnsugar** [comment]
不是的，因为需求等都不一样，我只是把一个单一知识点做了整理，相册和评论我分开了。
还有就是，评论没必要用listview，一个textview足矣，我给的方案就是一个text view实现的，listview是比较复杂的，不建议使用，你可以通过我写的东西，理解了SpannableString这个类，那么你自己写点赞功能也是很轻松的，也是只有一个text view，这样性能会提升不少，希望对你有帮助。

**Comment by shi88x** [comment]
评论怎么支持emoji？
