### ISSUE TITLE
支持emoji

### ISSUE THREAD

**Issue by shi88x** [hnsugar/CommentListTextView#2]
评论怎么支持emoji

**Comment by hnsugar** [comment]
默认textview就是支持emoji的，具体风格由系统rom决定，有的rom是和ios一致，有的rom是原生Android的，是谷歌提供的，如果要自己根据内容自定义添加emoji表情，你需要知道unicode编码，根据一定长度读出数据，判断数据对应的图片，再用imageSpan加载，添加到textview指定位置上，你可以参考emoji键盘的一些demo

**Comment by hnsugar** [comment]
也可以像qq微信那样自定义规范，特定字符串代表某一个表情，不过维护成本很高，与其他显示效果不兼容

**Comment by shi88x** [comment]
开始也想的自定义编码，在控件里面用正则匹配替换图片。为了方便就用默认的，不知道老版Android是不是支持不全，和ios 个别表情有兼容问题。

**Comment by hnsugar** [comment]
肯定有不能识别的，新的ios系统自己加了几十个表情，Android是没法匹配的，用一个默认图代替吧
