### ISSUE TITLE
点击名字没反应

### ISSUE THREAD

**Issue by Hn1993** [hnsugar/CommentListTextView#3]
点击名字没反应

**Comment by hnsugar** [comment]
首先确认一下是不是改过我的代码，如果直接导入的demo的话，是不是一直有日志在屏幕上显示，日志我记得是可以滑动的，但是必须手动滑动。如果从来没打印过任何日志，你可以排查一下是不是点击事件被拦截了或者你重复设置了覆盖了。

**Comment by Hn1993** [comment]
直接导入demo的时候有错误，运行不了，我是把View跟对应资源文件考到一个新项目里，然后点击无效

**Comment by hnsugar** [comment]
CommentListTextView.java这个类是需要的，MainActivity.java和对应布局不是必须的，setonCommentListener 是必须的设置的方法，还有setdata（），setonCommentListener 方法确定不会触发吗？你可以把你的activity文件给我，qq：1264957104
